### ISSUE TITLE
On pense avoir fini (Ne nous tapez pas trop fort, on a des lunettes)

### ISSUE THREAD

**Issue by RaphaelMARIENELLY** [PolytechLyon/2019-isi3-graph-marie-nelly_koualet#1]
Bonjour @Slashgear , 
Vous trouverez dans notre repository le projet ainsi que les réponses dans le compte rendu.
Merci d'avance de vos retours,

Bonne journée.

**Comment by Slashgear** [comment]
![gif](https://media.giphy.com/media/8ZkfimIBeq8g0A0BUD/giphy.gif)

**Comment by Slashgear** [comment]
- [ ] Les images ne s'affichent pas dans le rapport

- Sinon le reste c'est pas trop mal, ça passe pour cette fois.

> Je vous aurai un jour ! - Un prof qui vous attend au prochain piège 🤣

**Comment by Slashgear** [comment]
Ici, pourquoi devriez vous utiliser un IGraph comme attribut ?

https://github.com/PolytechLyon/2019-isi3-graph-marie-nelly_koualet/blob/bd08f0097d92abb2d23a4330168e4118b6b8f4d5/src/main/java/graph/UndirectedGraph.java#L8

**Comment by ajk11** [comment]
@Slashgear , 
Après avoir passer pas mal de temps à chercher, on pense que c’est mieux de définir graph en tant que IGraph et non DirectedGraph car cela apporte une meilleure généricité. Comme DirectedGraph implémente IDirectedGraph, qui lui-même est un héritage de IGraph, on pourra bien lui affecter un objet new DirectedGraph(). Mais l’avantage, c’est que si à l’avenir on souhaite créer une troisième classe de Graph qui hériterait de IGraph, on pourrait affecter à notre variable graph cette nouvelle classe et ne pas être limité (car si graph était de type DirectedGraph, graph ne pourrait pas avoir cette nouvelle classe de Graphe qui hérite de IGraph comme valeur).
Par contre, suite à cette modification, j’ai dû déclarer ces méthodes dans IGraph (comme me la gentiment suggéré IJ). Afin de ne pas faire de DRY, j’ai couper-coller les méthodes addArc et hasArc de IDirectedGraph dans IGraph. Puis dans la classe UndirectedGraph, j’ai implémenter les méthodes addArc() et hasArc().
